# Generated by Django 6.0.2 on 2026-02-15 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_applicationstatus_remove_faceverification_face_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeeperVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected')], help_text='Verification action taken', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required if action is rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the verification', null=True)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When verification was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of verifier (for audit)', null=True)),
                ('application', models.ForeignKey(help_text='Loan application being verified', on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeper_verifications', to='loans.loanapplication')),
                ('verified_by', models.ForeignKey(help_text='Bookkeeper who performed the verification', on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeper_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookkeeper Verification',
                'verbose_name_plural': 'Bookkeeper Verifications',
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['application', 'verified_at'], name='bookkeeper__applica_e09ebf_idx'), models.Index(fields=['verified_by', 'verified_at'], name='bookkeeper__verifie_0f7a25_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Full notification message')),
                ('notification_type', models.CharField(choices=[('new_application', 'New Application'), ('status_change', 'Status Change'), ('action_required', 'Action Required'), ('info', 'Information'), ('approval', 'Approval'), ('rejection', 'Rejection')], default='info', help_text='Type of notification for styling/filtering', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was marked as read', null=True)),
                ('related_application', models.ForeignKey(blank=True, help_text='Related loan application (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='loans.loanapplication')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='bookkeeper__user_id_ef46bf_idx'), models.Index(fields=['user', 'created_at'], name='bookkeeper__user_id_1bfb91_idx')],
            },
        ),
    ]
