# Generated by Django 6.0.1 on 2026-03-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_add_application_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_application', 'New Application'), ('status_change', 'Status Change'), ('action_required', 'Action Required'), ('info', 'Information'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('security_alert', 'Security Alert')], default='info', help_text='Type of notification for styling/filtering', max_length=20),
        ),
    ]
