# Generated by Django 6.0.1 on 2026-03-22 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0003_add_security_alert_notification_type'),
        ('loans', '0010_loanapplication_activated_at_and_more'),
        ('payments', '0002_remove_payment_amount_remove_payment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('disbursement', 'Loan Disbursement'), ('repayment', 'Loan Repayment'), ('closure', 'Loan Closure')], help_text='Type of accounting entry', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount recorded in this entry', max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this entry was recorded')),
                ('notes', models.TextField(blank=True, help_text='Optional bookkeeping notes')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='loans.loanapplication')),
                ('payment', models.OneToOneField(blank=True, help_text='Linked payment record (null for disbursement/closure entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entry', to='payments.payment')),
                ('recorded_by', models.ForeignKey(help_text='Bookkeeper who recorded this entry', on_delete=django.db.models.deletion.PROTECT, related_name='accounting_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Accounting Entry',
                'verbose_name_plural': 'Loan Accounting Entries',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['application', 'recorded_at'], name='bookkeeper__applica_00b920_idx'), models.Index(fields=['entry_type', 'recorded_at'], name='bookkeeper__entry_t_1b70ff_idx')],
            },
        ),
    ]
