# Generated by Django 6.0.3 on 2026-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0005_notification_archive_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeperverification',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('incomplete_docs', 'Incomplete Documentation'), ('invalid_docs', 'Invalid/Expired Documents'), ('insufficient_savings', 'Insufficient Savings'), ('insufficient_income', 'Insufficient Income'), ('employment_not_verified', 'Employment Not Verified'), ('others', 'Others')], help_text='Structured rejection category', max_length=30, null=True),
        ),
    ]
