# Generated by Django 6.0.1 on 2026-03-22 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0005_applicantprofile_coe_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('disciplinary', 'Disciplinary Termination'), ('voluntary', 'Voluntary Withdrawal'), ('deceased', 'Deceased')], max_length=15)),
                ('reason', models.TextField()),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination_record', to='applicant.member')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminations_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termination Record',
                'verbose_name_plural': 'Termination Records',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('failure_to_pay', 'Failure to Pay Obligations'), ('not_patronizing', 'Not Patronizing Cooperative Services'), ('policy_violation', 'Policy Violation'), ('fraud', 'Fraud / Suspicious Activity'), ('misconduct', 'Misconduct or Unethical Behavior'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('date_of_violation', models.DateField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='minor', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=15)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_logged', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='applicant.member')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Suspension'), ('termination', 'Termination'), ('reinstatement', 'Reinstatement')], max_length=15)),
                ('reason', models.TextField(help_text='Reason for this disciplinary action.')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('suspension_end_date', models.DateField(blank=True, help_text='End date for suspension (leave blank for indefinite).', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_decisions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='applicant.member')),
                ('violations', models.ManyToManyField(blank=True, help_text='Violations that led to this action.', related_name='disciplinary_actions', to='superadmin.violation')),
            ],
            options={
                'verbose_name': 'Disciplinary Action',
                'verbose_name_plural': 'Disciplinary Actions',
                'ordering': ['-decided_at'],
            },
        ),
    ]
