# Generated by Django 6.0.3 on 2026-04-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('users', '0009_remove_user_employee_id_adminuser_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='users.applicant'),
        ),
        migrations.AlterField(
            model_name='terminationrecord',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination_record', to='users.applicant'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='users.applicant'),
        ),
    ]
