# Generated by Django 6.0.1 on 2026-02-16 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0003_loanapplication_forwarded_to_treasurer_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCommitteeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned to Treasurer')], help_text='Committee decision', max_length=20)),
                ('remarks', models.TextField(help_text='Required remarks explaining the decision')),
                ('meeting_date', models.DateField(help_text='Date of committee meeting when decision was made')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when decision was recorded')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for audit trail', null=True)),
                ('application', models.ForeignKey(help_text='Loan application being decided', on_delete=django.db.models.deletion.CASCADE, related_name='credit_committee_decisions', to='loans.loanapplication')),
                ('decided_by', models.ForeignKey(help_text='Committee member who made the decision', on_delete=django.db.models.deletion.PROTECT, related_name='credit_committee_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Committee Decision',
                'verbose_name_plural': 'Credit Committee Decisions',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['application', 'decided_at'], name='credit_comm_applica_ee91ee_idx'), models.Index(fields=['decided_by', 'decided_at'], name='credit_comm_decided_ac781a_idx'), models.Index(fields=['decision', 'decided_at'], name='credit_comm_decisio_84d767_idx')],
            },
        ),
    ]
