# Generated by Django 6.0.3 on 2026-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_committee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcommitteedecision',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('incomplete_docs', 'Incomplete Documentation'), ('invalid_docs', 'Invalid/Expired Documents'), ('insufficient_savings', 'Insufficient Savings'), ('insufficient_income', 'Insufficient Income'), ('employment_not_verified', 'Employment Not Verified'), ('high_dti', 'High Debt-to-Income Ratio'), ('does_not_meet_credit', 'Does Not Meet Credit Requirements'), ('others', 'Others')], help_text='Structured rejection category (applicable when decision is rejected)', max_length=30, null=True),
        ),
    ]
