# Generated by Django 6.0.2 on 2026-03-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_member_officer', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='amonotification',
            new_name='account_mem_user_id_327b86_idx',
            old_name='amo_notif_user_isread_idx',
        ),
    ]
