"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gngn*p81m4pj)2r5j094rm-9cfioite&b(%761addw^#3j!$%g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.255.9.60',
    '10.0.0.52',
]


# Application definition

INSTALLED_APPS = [
    # Admin interface (must be before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',  # Optional: advanced filters
    'unfold.contrib.forms',    # Optional: enhanced forms

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django.contrib.humanize',

    # Local apps
    'users',
    'loans',
    'payments',
    'authentication',
    'reports',
    'bookkeeper',
    'treasurer',
    'credit_committee',
    'applicant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eloan_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eloan_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # Read DB connection from environment variables so you can point
        # this Django project to any local or remote MySQL/MariaDB server.
        'NAME': os.environ.get('DB_NAME', 'eloan'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# REST Framework and JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# For development: emails will be printed to console
# For production: configure SMTP settings in .env file

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'  # Default: print to console
)

# SMTP Configuration (for production with real email sending)
# Set EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend' in .env to use these
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@eloan.com')

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# CORS Configuration
# Allow requests from the frontend application and mobile app
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',       # Web frontend
    'http://127.0.0.1:3000',       # Web frontend
    'http://10.255.9.60:3000',   # Web frontend (network access)
    'http://localhost:8081',       # Expo dev server (default)
    'http://127.0.0.1:8081',       # Expo dev server
    'http://localhost:19000',      # Expo dev server (alternative port)
    'http://localhost:19006',      # Expo web
]

# For development, you can use CORS_ALLOW_ALL_ORIGINS = True
# But for production, always specify exact origins above
CORS_ALLOW_CREDENTIALS = True

# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "eLoan Administration",
    "SITE_HEADER": "eLoan Super Admin",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "💰",  # Icon for light mode
        "dark": lambda request: "💰",   # Icon for dark mode
    },
    "SITE_LOGO": {
        "light": lambda request: "💰 eLoan",  # Logo for light mode
        "dark": lambda request: "💰 eLoan",   # Logo for dark mode
    },
    "SITE_SYMBOL": "💰",  # Symbol in top left corner
    "SHOW_HISTORY": True,  # Show history button
    "SHOW_VIEW_ON_SITE": True,  # Show view on site button
    "ENVIRONMENT": "development",
    "DASHBOARD_CALLBACK": None,
    "STYLES": [
        lambda request: "/static/css/custom-admin.css",  # Custom CSS if needed
    ],
    "SCRIPTS": [],
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",  # Main purple color
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Search in sidebar
        "show_all_applications": True,  # Show all applications
        "navigation": [
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": lambda request: "/admin/users/user/",
                    },
                    {
                        "title": "Roles",
                        "icon": "badge",
                        "link": lambda request: "/admin/users/role/",
                    },
                ],
            },
            {
                "title": "Member Management",
                "separator": True,
                "items": [
                    {
                        "title": "Pending Registrations",
                        "icon": "pending_actions",
                        "link": lambda request: "/admin/users/user/?account_status__exact=pending",
                    },
                    {
                        "title": "All Members",
                        "icon": "people",
                        "link": lambda request: "/admin/applicant/member/",
                    },
                    {
                        "title": "Savings Records",
                        "icon": "savings",
                        "link": lambda request: "/admin/applicant/savings/",
                    },
                    {
                        "title": "Shared Capital",
                        "icon": "account_balance",
                        "link": lambda request: "/admin/applicant/sharedcapital/",
                    },
                ],
            },
            {
                "title": "Loan Management",
                "separator": True,
                "items": [
                    {
                        "title": "Loan Applications",
                        "icon": "description",
                        "link": lambda request: "/admin/loans/loanapplication/",
                    },
                    {
                        "title": "Loan Types",
                        "icon": "category",
                        "link": lambda request: "/admin/loans/loantype/",
                    },
                    {
                        "title": "Application Status",
                        "icon": "flag",
                        "link": lambda request: "/admin/loans/applicationstatus/",
                    },
                    {
                        "title": "Documents",
                        "icon": "folder",
                        "link": lambda request: "/admin/loans/loandocument/",
                    },
                ],
            },
            {
                "title": "Payments",
                "separator": True,
                "items": [
                    {
                        "title": "All Payments",
                        "icon": "payments",
                        "link": lambda request: "/admin/payments/payment/",
                    },
                ],
            },
            {
                "title": "Reports & Analytics",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": lambda request: "/admin/reports/dashboard/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "users.user",
            ],
            "items": [
                {
                    "title": "All Users",
                    "link": lambda request: "/admin/users/user/",
                },
                {
                    "title": "Pending Approval",
                    "link": lambda request: "/admin/users/user/?account_status__exact=pending",
                },
                {
                    "title": "Approved",
                    "link": lambda request: "/admin/users/user/?account_status__exact=approved",
                },
                {
                    "title": "Rejected",
                    "link": lambda request: "/admin/users/user/?account_status__exact=rejected",
                },
                {
                    "title": "Suspended",
                    "link": lambda request: "/admin/users/user/?status__exact=suspended",
                },
            ],
        },
    ],
}
