"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Google OAuth — Web Client ID used to verify the `aud` claim in ID tokens
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')

# Google reCAPTCHA v2 — Secret key used for server-side token verification
# Get keys at: https://www.google.com/recaptcha/admin
RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='')
# Set RECAPTCHA_BYPASS=True in .env to skip CAPTCHA checks during development/testing
RECAPTCHA_BYPASS = config('RECAPTCHA_BYPASS', default=False, cast=bool)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# HTTPS / cookie security — set these to True in production via .env
# Safe to leave False in development (HTTP); enforced when behind TLS in production
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# Security headers set by Django's SecurityMiddleware
SECURE_CONTENT_TYPE_NOSNIFF = True        # X-Content-Type-Options: nosniff
SECURE_BROWSER_XSS_FILTER = True          # X-XSS-Protection: 1; mode=block (legacy, harmless)
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Referrer-Policy
X_FRAME_OPTIONS = 'DENY'                  # Reinforces XFrameOptionsMiddleware

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='*',
    cast=lambda v: [h.strip() for h in v.split(',') if h.strip()],
)
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Admin interface (must be before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',  # Optional: advanced filters
    'unfold.contrib.forms',    # Optional: enhanced forms

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django.contrib.humanize',

    # Local apps
    'users',
    'loans',
    'payments',
    'authentication',
    'reports',
    'bookkeeper',
    'treasurer',
    'credit_committee',
    'applicant',
    'account_member_officer',
    'superadmin',
    # 'members',  # Disabled: duplicate models with applicant app
]

MIDDLEWARE = [
    'eloan_core.middleware.CORSAndCoopMiddleware',  # COOP headers for Google OAuth popups
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eloan_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eloan_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # Read DB connection from environment variables so you can point
        # this Django project to any local or remote MySQL/MariaDB server.
        'NAME': config('DB_NAME', default='eloan'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# REST Framework and JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'eloan_core.exceptions.eloan_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        # Auth endpoints (anonymous / pre-login)
        'login': '5/min',
        'registration': '10/hour',
        'password_reset': '5/hour',
        # Applicant API endpoints (authenticated)
        'face_verification': '20/hour',
        'liveness_check': '20/hour',
        'document_upload': '10/hour',
        'id_ocr': '5/hour',
        'burst': '30/min',
        'sustained': '100/hour',
        # Anonymous general
        'anon_burst': '10/min',
        'anon_sustained': '30/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Face Verification Settings
FACE_VERIFICATION = {
    'ENABLED': True,
    # ArcFace cosine distance interpretation (lower = more similar, 0 = identical):
    #   <= 0.50  → Verified        (clear match, high confidence)
    #   0.50–0.68 → Needs Review   (borderline — bookkeeper decides)
    #   >  0.68  → Failed          (ArcFace documented same-person threshold is 0.68;
    #                               anything above is statistically a different person)
    'AUTO_APPROVE_MAX_DISTANCE': 0.50,
    'REVIEW_MAX_DISTANCE': 0.68,
    'MODEL': 'ArcFace',
    'DISTANCE_METRIC': 'cosine',
    # yunet weights already downloaded to ~/.deepface/weights/face_detection_yunet_2023mar.onnx
    'DETECTOR_BACKEND': 'yunet',
    'UNLIMITED_RETRIES': True,  # Allow unlimited retry attempts
}

# Liveness Detection Settings (MediaPipe)
LIVENESS_DETECTION = {
    'ENABLED': True,
    'MIN_CONFIDENCE_THRESHOLD': 70,  # Minimum confidence % to pass liveness check
    'EAR_THRESHOLD': 0.21,  # Eye Aspect Ratio threshold (below = eyes closed)
    'HEAD_TURN_THRESHOLD': 15,  # Max yaw angle in degrees for natural pose
    'HEAD_NOD_THRESHOLD': 10,  # Max pitch angle in degrees for natural pose
    'DEFAULT_METHOD': 'combined',  # Default detection method: blink, head_turn, combined
}

# File Encryption Settings
# CRITICAL: ENCRYPTION_KEY must be set in .env — never change it or all encrypted files become unreadable.
# Generate a key once: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

ENCRYPTION_KEY = config('ENCRYPTION_KEY')  # No default — server will refuse to start if missing

# Cache Configuration (for rate limiting)
# For development: use in-memory cache
# For production: use Redis for better performance and persistence
CACHES = {
    'default': {
        'BACKEND': config(
            'CACHE_BACKEND',
            default='django.core.cache.backends.locmem.LocMemCache'
        ),
        'LOCATION': config('CACHE_LOCATION', default='eloan-cache'),
        # For Redis in production, use:
        # 'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        # 'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

# Cache TTLs (seconds) — override via environment variables if needed.
CACHE_TTL_LOAN_TYPES     = config('CACHE_TTL_LOAN_TYPES',     default=300,  cast=int)  # 5 min
CACHE_TTL_REQUIRED_DOCS  = config('CACHE_TTL_REQUIRED_DOCS',  default=600,  cast=int)  # 10 min
CACHE_TTL_NOTIFICATIONS  = config('CACHE_TTL_NOTIFICATIONS',  default=60,   cast=int)  # 1 min

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging — security events written to logs/security.log (rotating, 10 MB × 5 files)
_LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(_LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} [{name}] {message}',
            'style': '{',
        },
        'security': {
            'format': '{asctime} SECURITY {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(_LOGS_DIR, 'security.log'),
            'maxBytes': 10 * 1024 * 1024,   # 10 MB per file
            'backupCount': 5,                # keep last 5 rotations
            'formatter': 'security',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'encryption': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'face_verification': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Email Configuration
# For development: emails will be printed to console
# For production: configure SMTP settings in .env file

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'  # Default: print to console
)

# SMTP Configuration (for production with real email sending)
# Set EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend' in .env to use these
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@eloan.com')

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# CORS Configuration
# Allow requests from the frontend application and mobile app
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:8081,http://localhost:19000,http://localhost:19006',
    cast=lambda v: [o.strip() for o in v.split(',') if o.strip()],
)
CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "eLoan Administration",
    "SITE_HEADER": "eLoan Admin Console",
    "SITE_URL": "/",
    "SITE_SYMBOL": "account_balance",  # Material Symbols icon in sidebar header
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "development",
    "DASHBOARD_CALLBACK": None,
    "STYLES": [
        lambda request: "/static/css/custom-admin.css",
    ],
    "SCRIPTS": [],
    # eLoan brand color scale — navy #02327a as the 700 anchor
    "COLORS": {
        "primary": {
            "50":  "236 244 255",
            "100": "213 232 255",
            "200": "172 209 255",
            "300": "108 173 255",
            "400": "52  126 246",
            "500": "14  88  210",
            "600": "8   65  175",
            "700": "2   50  122",   # #02327a — eLoan brand
            "800": "1   38  95",
            "900": "1   28  70",
            "950": "1   18  46",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": lambda request: "/admin/users/user/",
                    },
                    {
                        "title": "Roles",
                        "icon": "badge",
                        "link": lambda request: "/admin/users/role/",
                    },
                    {
                        "title": "Pending Approval",
                        "icon": "pending_actions",
                        "link": lambda request: "/admin/users/user/?account_status__exact=pending",
                    },
                ],
            },
            {
                "title": "Member Management",
                "separator": True,
                "items": [
                    {
                        "title": "All Members",
                        "icon": "people",
                        "link": lambda request: "/admin/applicant/member/",
                    },
                    {
                        "title": "Savings Records",
                        "icon": "savings",
                        "link": lambda request: "/admin/applicant/savings/",
                    },
                    {
                        "title": "Shared Capital",
                        "icon": "account_balance",
                        "link": lambda request: "/admin/applicant/sharedcapital/",
                    },
                ],
            },
            {
                "title": "Loan Management",
                "separator": True,
                "items": [
                    {
                        "title": "Loan Applications",
                        "icon": "description",
                        "link": lambda request: "/admin/loans/loanapplication/",
                    },
                    {
                        "title": "Loan Types",
                        "icon": "category",
                        "link": lambda request: "/admin/loans/loantype/",
                    },
                    {
                        "title": "Application Status",
                        "icon": "flag",
                        "link": lambda request: "/admin/loans/applicationstatus/",
                    },
                    {
                        "title": "Documents",
                        "icon": "folder",
                        "link": lambda request: "/admin/loans/loandocument/",
                    },
                ],
            },
            {
                "title": "Payments",
                "separator": True,
                "items": [
                    {
                        "title": "All Payments",
                        "icon": "payments",
                        "link": lambda request: "/admin/payments/payment/",
                    },
                ],
            },
            {
                "title": "Disciplinary",
                "separator": True,
                "items": [
                    {
                        "title": "Violations",
                        "icon": "gavel",
                        "link": lambda request: "/admin/superadmin/violation/",
                    },
                    {
                        "title": "Disciplinary Actions",
                        "icon": "policy",
                        "link": lambda request: "/admin/superadmin/disciplinaryaction/",
                    },
                    {
                        "title": "Termination Records",
                        "icon": "person_remove",
                        "link": lambda request: "/admin/superadmin/terminationrecord/",
                    },
                ],
            },
            {
                "title": "Reports & Analytics",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": lambda request: "/admin/reports/dashboard/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": ["users.user"],
            "items": [
                {
                    "title": "All Users",
                    "link": lambda request: "/admin/users/user/",
                },
                {
                    "title": "Pending Approval",
                    "link": lambda request: "/admin/users/user/?account_status__exact=pending",
                },
                {
                    "title": "Approved",
                    "link": lambda request: "/admin/users/user/?account_status__exact=approved",
                },
                {
                    "title": "Rejected",
                    "link": lambda request: "/admin/users/user/?account_status__exact=rejected",
                },
                {
                    "title": "Suspended",
                    "link": lambda request: "/admin/users/user/?status__exact=suspended",
                },
            ],
        },
        {
            "models": ["superadmin.violation"],
            "items": [
                {
                    "title": "All Violations",
                    "link": lambda request: "/admin/superadmin/violation/",
                },
                {
                    "title": "Open",
                    "link": lambda request: "/admin/superadmin/violation/?status__exact=open",
                },
                {
                    "title": "Escalated",
                    "link": lambda request: "/admin/superadmin/violation/?status__exact=escalated",
                },
                {
                    "title": "Resolved",
                    "link": lambda request: "/admin/superadmin/violation/?status__exact=resolved",
                },
            ],
        },
    ],
}

# ---------------------------------------------------------------------------
# Startup environment variable validation
# ---------------------------------------------------------------------------
# Fail fast with a clear message if any critical variable is missing or empty.
# python-decouple already raises UndefinedValueError for vars with no default,
# but this catches empty-string assignments (e.g. SECRET_KEY=) and lists all
# missing vars in one error instead of failing one at a time.
# ---------------------------------------------------------------------------
from django.core.exceptions import ImproperlyConfigured  # noqa: E402

_REQUIRED_VARS = {
    'SECRET_KEY': SECRET_KEY,
    'GOOGLE_CLIENT_ID': GOOGLE_CLIENT_ID,
    'ENCRYPTION_KEY': ENCRYPTION_KEY,
}

_missing = [name for name, val in _REQUIRED_VARS.items() if not val]
if _missing:
    raise ImproperlyConfigured(
        '\n\nThe following required environment variables are not set or are empty:\n'
        + '\n'.join(f'  - {name}' for name in _missing)
        + '\n\nSet them in your .env file. See backend/.env.example for reference.'
    )
