# Generated by Django 6.0.1 on 2026-02-04 08:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='faceverification',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='faceverification',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='livenesscheck',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='livenesscheck',
            name='video_clip',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='term_days',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='term_days',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='faceverification',
            name='captured_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='verification_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='check_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_amortization',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='term_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loantype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loantype',
            name='loan_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loantype',
            name='max_term_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loantype',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to='loans.loanapplication'),
        ),
        migrations.AlterField(
            model_name='livenesscheck',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_checks', to='loans.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='loans.loantype'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.applicationstatus'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCoMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comakers', to='loans.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'user')},
            },
        ),
    ]
