# Generated by Django 6.0.2 on 2026-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_applicationstatus_remove_faceverification_face_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='forwarded_to_treasurer_at',
            field=models.DateTimeField(blank=True, help_text='When application was forwarded to treasurer', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net monthly salary from payslip', max_digits=12, null=True),
        ),
    ]
