# Generated by Django 6.0.1 on 2026-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanapplication_forwarded_to_treasurer_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loantype',
            options={'ordering': ['loan_name']},
        ),
        migrations.AddField(
            model_name='loantype',
            name='required_comakers',
            field=models.IntegerField(default=0, help_text='Number of co-makers required for this loan type'),
        ),
    ]
