# Generated by Django 6.0.2 on 2026-02-23 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loantype_options_loantype_required_comakers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by_role', models.CharField(blank=True, help_text='Role of the user who made the change', max_length=50, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks/reason for status change', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_logs', to='loans.loanapplication')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(blank=True, help_text='Previous status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_from', to='loans.applicationstatus')),
                ('to_status', models.ForeignKey(blank=True, help_text='New status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_to', to='loans.applicationstatus')),
            ],
            options={
                'verbose_name': 'Status Change Log',
                'verbose_name_plural': 'Status Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['application', 'changed_at'], name='loans_statu_applica_30136d_idx'), models.Index(fields=['changed_by', 'changed_at'], name='loans_statu_changed_2c0f1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusTransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_role', models.CharField(help_text='Role allowed to make this transition (e.g., Applicant, Bookkeeper, Treasurer, Credit Committee)', max_length=50)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_rules_from', to='loans.applicationstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_rules_to', to='loans.applicationstatus')),
            ],
            options={
                'verbose_name': 'Status Transition Rule',
                'verbose_name_plural': 'Status Transition Rules',
                'unique_together': {('from_status', 'to_status', 'allowed_role')},
            },
        ),
    ]
