# Generated by Django 6.0.2 on 2026-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_status_change_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverification',
            name='comparison_distance',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Raw distance metric from DeepFace', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='comparison_model',
            field=models.CharField(default='ArcFace', help_text='Face comparison model used', max_length=50),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='comparison_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Threshold used for verification', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if verification failed', null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='face_detected_in_id',
            field=models.BooleanField(default=False, help_text='Whether a face was detected in ID photo'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='face_detected_in_selfie',
            field=models.BooleanField(default=False, help_text='Whether a face was detected in selfie'),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='id_photo_path',
            field=models.CharField(blank=True, help_text='Path to ID photo extracted from document', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='is_match',
            field=models.BooleanField(blank=True, help_text='Whether faces match based on threshold', null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When face comparison was performed', null=True),
        ),
        migrations.AddField(
            model_name='faceverification',
            name='similarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DeepFace similarity score (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='captured_image_path',
            field=models.CharField(blank=True, help_text='Path to captured selfie', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faceverification',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy match score field', max_digits=5, null=True),
        ),
    ]
