# Generated by Django 6.0.2 on 2026-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_faceverification_comparison_distance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livenesscheck',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='avg_ear',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Average Eye Aspect Ratio', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='detection_details',
            field=models.TextField(blank=True, help_text='JSON details from MediaPipe detection', null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if check failed', null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='eyes_open',
            field=models.BooleanField(blank=True, help_text='Whether eyes were detected as open', null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='head_pitch',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Head pitch angle in degrees', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='head_roll',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Head roll angle in degrees', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='head_yaw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Head yaw angle in degrees', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path to the liveness check image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='left_ear',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Left Eye Aspect Ratio', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='livenesscheck',
            name='right_ear',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Right Eye Aspect Ratio', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='livenesscheck',
            name='check_status',
            field=models.CharField(default='Pending', help_text='Pending, Verified, or Failed', max_length=20),
        ),
        migrations.AlterField(
            model_name='livenesscheck',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score 0-100', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='livenesscheck',
            name='method',
            field=models.CharField(blank=True, help_text='Detection method: blink, head_turn, head_nod, combined', max_length=20, null=True),
        ),
    ]
