# Generated by Django 6.0.2 on 2026-03-15 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_add_liveness_detection_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('APPLICATION_SUBMIT', 'Application Submitted'), ('APPLICATION_WITHDRAW', 'Application Withdrawn'), ('APPLICATION_DELETE', 'Application Deleted'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('DOCUMENT_DELETE', 'Document Deleted'), ('FACE_VERIFY_SUCCESS', 'Face Verification Success'), ('FACE_VERIFY_FAIL', 'Face Verification Failed'), ('LIVENESS_SUCCESS', 'Liveness Check Success'), ('LIVENESS_FAIL', 'Liveness Check Failed'), ('RATE_LIMIT_HIT', 'Rate Limit Exceeded'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity Detected'), ('PDF_DOWNLOAD', 'PDF Downloaded'), ('OTHER', 'Other Action')], db_index=True, help_text='Categorized action type for filtering and reporting', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Detailed reason for failure (if success=False)', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='related_application',
            field=models.ForeignKey(blank=True, help_text='Related loan application (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ALERT', 'Alert'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', help_text='Severity level of the action', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the action completed successfully'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(help_text='Human-readable description of the action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, help_text='IP address of the request', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action_type', 'timestamp'], name='loans_audit_user_id_9ce630_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'success', 'timestamp'], name='loans_audit_action__e0164f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['related_application', 'action_type'], name='loans_audit_related_f43d51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='loans_audit_severit_98b32f_idx'),
        ),
    ]
