# Generated by Django 6.0.1 on 2026-03-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_auditlog_options_auditlog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='first_installment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='installment_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('semi_monthly', 'Semi-Monthly (Every 15 days)')], default='monthly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_form_data',
            field=models.JSONField(blank=True, help_text='Loan-type-specific form fields (e.g., share capital, ATM collateral details, LAD encumbered deposit)', null=True),
        ),
        migrations.CreateModel(
            name='LoanTypeRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(help_text='Matches DocumentTypes constant keys', max_length=60)),
                ('document_label', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='loans.loantype')),
            ],
            options={
                'verbose_name': 'Loan Type Required Document',
                'verbose_name_plural': 'Loan Type Required Documents',
                'ordering': ['sort_order', 'document_label'],
                'unique_together': {('loan_type', 'document_key')},
            },
        ),
    ]
