# Generated by Django 6.0.1 on 2026-03-22 09:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loanapplication_first_installment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='activated_at',
            field=models.DateField(blank=True, help_text='Date the loan became Active (funds released)', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_health_status',
            field=models.CharField(blank=True, choices=[('on_time', 'On Time'), ('late', 'Late'), ('overdue', 'Overdue'), ('delinquent', 'Delinquent')], help_text='Payment health: on_time, late (<30 days), overdue (30-90 days), delinquent (>90 days)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='Sequential installment number (1, 2, 3, ...)')),
                ('due_date', models.DateField(help_text='Date this installment is due')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Total amount due for this installment', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid towards this installment', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('late', 'Late'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When this installment was fully paid', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Payment Schedule',
                'verbose_name_plural': 'Payment Schedules',
                'ordering': ['installment_number'],
                'unique_together': {('application', 'installment_number')},
            },
        ),
    ]
