# Generated by Django 6.0.2 on 2026-02-18 02:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0003_loanapplication_forwarded_to_treasurer_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_address', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('years_employed', models.IntegerField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
            },
        ),
        migrations.CreateModel(
            name='CoMakerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship_to_applicant', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_type', models.CharField(choices=[('philippine_id', 'Philippine National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('sss_id', 'SSS ID'), ('philhealth_id', 'PhilHealth ID'), ('voters_id', "Voter's ID"), ('postal_id', 'Postal ID'), ('prc_id', 'PRC ID'), ('other', 'Other Government ID')], max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('id_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_comaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_info', to='loans.loancomaker')),
            ],
            options={
                'verbose_name': 'Co-Maker Information',
                'verbose_name_plural': 'Co-Maker Information',
            },
        ),
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image_path', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esignature', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'E-Signature',
                'verbose_name_plural': 'E-Signatures',
            },
        ),
        migrations.CreateModel(
            name='LoanTypeCoMakerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_comakers', models.IntegerField(default=0, help_text='Number of co-makers required (0, 1, or 2)')),
                ('loan_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comaker_requirement', to='loans.loantype')),
            ],
            options={
                'verbose_name': 'Loan Type Co-Maker Requirement',
                'verbose_name_plural': 'Loan Type Co-Maker Requirements',
            },
        ),
    ]
