# Generated by Django 6.0.1 on 2026-03-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_member_membershipapprovallog_savings_sharedcapital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESignature',
        ),
    ]
