# Generated by Django 6.0.1 on 2026-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_remove_esignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('casual', 'Casual'), ('part_time', 'Part-Time'), ('job_order', 'Job Order')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='net_take_home_pay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net take-home pay after deductions', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comakerinfo',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('td_savings', 'TD/Savings')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comakerinfo',
            name='bank_reference_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comakerinfo',
            name='no_of_dependents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comakerinfo',
            name='other_income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='comakerinfo',
            name='other_income_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comakerinfo',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comakerinfo',
            name='years_in_address',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
