# Generated by Django 6.0.1 on 2026-03-22 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_applicantprofile_civil_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='coe_document',
            field=models.FileField(blank=True, help_text='Certificate of Employment or proof of employment status', null=True, upload_to='membership_documents/coe/'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='membership_form',
            field=models.FileField(blank=True, help_text='Accomplished membership application form', null=True, upload_to='membership_documents/forms/'),
        ),
        migrations.AddField(
            model_name='member',
            name='employment_status_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='employment_status_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_verifications_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='fixed_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed deposit in PHP. >= 20,000 qualifies for Regular membership (if employment status allows).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('warned', 'Warned'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('voluntary_withdrawal', 'Voluntary Withdrawal'), ('deceased', 'Deceased')], default='active', max_length=25),
        ),
        migrations.AddField(
            model_name='member',
            name='verified_employment_status',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('casual', 'Casual'), ('part_time', 'Part-Time / Contract of Service'), ('job_order', 'Job Order')], help_text='Employment status verified by Account Member Officer after reviewing COE/proof.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapprovallog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_approved', 'Appeal Approved'), ('appeal_rejected', 'Appeal Rejected')], max_length=20),
        ),
        migrations.CreateModel(
            name='MembershipAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for appeal submitted by the applicant.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_appeal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Appeal',
                'verbose_name_plural': 'Membership Appeals',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
