# Generated by Django 6.0.3 on 2026-04-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_member_share_fields'),
        ('users', '0010_migrate_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantbeneficiary',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='users.applicant'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='employment_status_verified_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterField(
            model_name='savings',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_records', to='users.applicant'),
        ),
        migrations.AlterField(
            model_name='sharedcapital',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_capital_records', to='users.applicant'),
        ),
        migrations.DeleteModel(
            name='ApplicantProfile',
        ),
    ]
