# Generated by Django 6.0.3 on 2026-04-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicantbeneficiary_profile_and_more'),
        ('superadmin', '0002_alter_disciplinaryaction_member_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
