# Generated by Django 6.0.2 on 2026-03-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='treasurerevaluation',
            new_name='treasurer_t_applica_681994_idx',
            old_name='treasurer_t_applica_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurerevaluation',
            new_name='treasurer_t_evaluat_36098b_idx',
            old_name='treasurer_t_evaluat_idx',
        ),
    ]
