# Generated by Django 6.0.3 on 2026-04-02 10:07

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_account_member_officer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'users_admin',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_province', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship', models.CharField(blank=True, default='Filipino', max_length=50, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('tin', models.CharField(blank=True, help_text='Tax Identification Number', max_length=20, null=True)),
                ('sss_number', models.CharField(blank=True, help_text='SSS Number', max_length=30, null=True)),
                ('highest_education', models.CharField(blank=True, choices=[('elementary', 'Elementary'), ('high_school', 'High School'), ('vocational', 'Vocational/Technical'), ('college', 'College'), ('post_graduate', 'Post-Graduate')], max_length=20, null=True)),
                ('employment_category', models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-Teaching'), ('others', 'Others')], max_length=20, null=True)),
                ('employment_status', models.CharField(choices=[('regular', 'Regular'), ('casual', 'Casual'), ('job_order', 'Job Order'), ('part_time', 'Part-time')], default='regular', max_length=20)),
                ('buksu_id_number', models.CharField(blank=True, help_text='BukSU ID Number', max_length=50, null=True)),
                ('office', models.CharField(blank=True, help_text='Office/Department', max_length=100, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_address', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_take_home_pay', models.DecimalField(blank=True, decimal_places=2, help_text='Net take-home pay after deductions', max_digits=12, null=True)),
                ('years_employed', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='applicant_documents/id_photos/')),
                ('payslip', models.FileField(blank=True, null=True, upload_to='applicant_documents/payslips/')),
                ('coe_document', models.FileField(blank=True, null=True, upload_to='membership_documents/coe/')),
                ('membership_form', models.FileField(blank=True, null=True, upload_to='membership_documents/forms/')),
                ('membership_type', models.CharField(choices=[('associate', 'Associate Member'), ('regular', 'Regular Member')], default='associate', max_length=20)),
                ('fixed_deposit', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed deposit in PHP. >= 20,000 qualifies for Regular membership.', max_digits=12, null=True)),
                ('verified_employment_status', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('casual', 'Casual'), ('part_time', 'Part-Time / Contract of Service'), ('job_order', 'Job Order')], help_text='Employment status verified by Account Member Officer after reviewing COE/proof.', max_length=20, null=True)),
                ('employment_status_verified_at', models.DateTimeField(blank=True, null=True)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('warned', 'Warned'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('voluntary_withdrawal', 'Voluntary Withdrawal'), ('deceased', 'Deceased')], default='active', max_length=25)),
                ('subscribed_shares', models.PositiveIntegerField(blank=True, help_text='Number of shares subscribed. Minimum: 20 (By-Laws Section 3c & 6).', null=True)),
                ('paid_shares', models.PositiveIntegerField(blank=True, help_text='Number of shares paid up. Minimum: 5 (By-Laws Section 3c & 6).', null=True)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('profile_created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_updated_at', models.DateTimeField(auto_now=True)),
                ('employment_status_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'users_applicant',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
