# Generated by Django 6.0.3 on 2026-04-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_missing_staff_roles'),
        ('users', '0011_add_staff_roles'),
    ]

    operations = [
    ]
